# Generated by Django 2.2 on 2019-05-07 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190507_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 7, 2, 9, 340156, tzinfo=utc)),
        ),
    ]
